[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hqai"
version = "0.1.0"
description = "Hanaka Quant AI"
requires-python = ">=3.12"

dependencies = [
    "typer>=0.16",
    "rich>=14.0"
]

[project.scripts]
hqai = "hqai.cli.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
